// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Munter.Core.Data;

namespace Munter.Core.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Munter.Core.Data.Entities.SearchResponse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("JsonData")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchText")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("SearchResponses");
                });

            modelBuilder.Entity("Munter.Core.Data.Entities.TrendingResponse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("JsonData")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TrendingResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
